name: Twitter Sentiment Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sentiment_analysis:
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - shell: python
      run: "import os ; print(list(os.environ))"

    - env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      shell: python
      run: "import os ; print(list(os.environ))"

      
    - if: ${{ env.ACCESS_KEY != '' }}
      run: echo 'This step will only run if the secret has a value set.'
    - if: ${{ env.ACCESS_KEY == '' }}
      run: echo 'This step will only run if the secret does not have a value set.'

    - env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
      run: echo This event is a pull request that had an assignee removed.
   
   - env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      shell: python
      run: "import os ; print(os.environ) ; assert os.getenv('ACCESS_KEY') or os.getenv('ACCESS_KEY')"

    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tweet extraction process
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      run: |
        python add_tweets_1.py
        python add_sentiment_to_tweets_2.py

    - name: Run recommendation method
      run: |
        python recommender_function_6.py

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: rohan472000
        author_email: anand00rohan@example.com
        message: Updated sentiment analysis data
        add: 'updated_reftweets.csv'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
